spring:
  application:
    name: Payment
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, custom-metrics


